version: "3.7"

services:
  smartcalc_pg:
    image: postgres:14
    container_name: smartcalc_pg
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dbsmartcalculator
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - smartcalc

  smartcalc_redis:
    image: redis:6.2.6
    container_name: smartcalc_redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - smartcalc

  micro_mock:
    image: wiremock/wiremock:3.7.0
    container_name: micro-mock
    ports:
      - "8081:8080"
    volumes:
      - ./micro-mock/__files:/home/wiremock/__files
      - ./micro-mock/mappings:/home/wiremock/mappings
    command: --verbose
    networks:
      - smartcalc

  micro_smartcalc:
    container_name: micro_smartcalc
    depends_on:
      - smartcalc_pg
      - smartcalc_redis
      - micro_mock
    build:
      context: ./smartcalc/
      dockerfile: Dockerfile
    ports:
      - "9002:8080"
    environment:
      - spring.datasource.url=jdbc:postgresql://smartcalc_pg:5432/dbsmartcalculator
      - spring.datasource.username=postgres
      - spring.datasource.password=postgres
      - server.port=8080
      - spring.redis.host=smartcalc_redis
      - spring.redis.port=6379
      - tec.cache.redis.memory.storage.time=30
      - tec.external.endPoint.percentage=http://micro_mock:8080/calculator
    restart: always
    networks:
      - smartcalc

networks:
  smartcalc:
    driver: bridge
